// Date: 2017/2/7 20:01:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class ModelJuQue extends ModelBase
{
  //fields
    ModelRenderer jianjian1;
    ModelRenderer jianjian2;
    ModelRenderer jianjian3;
    ModelRenderer jianjian41;
    ModelRenderer jianjian42;
    ModelRenderer jianduan1;
    ModelRenderer jianduan2;
    ModelRenderer jianbingg;
    ModelRenderer jiange1;
    ModelRenderer jiange2;
    ModelRenderer jiansheng1;
    ModelRenderer jiansheng2;
    ModelRenderer jiansheng3;
    ModelRenderer jiansheng4;
    ModelRenderer jiansheng5;
    ModelRenderer jiansheng6;
    ModelRenderer jiansheng7;
  
  public ModelJuQue()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      jianjian1 = new ModelRenderer(this, 37, 73);
      jianjian1.addBox(-3F, -3F, 0F, 6, 6, 4);
      jianjian1.setRotationPoint(0F, 6F, -2F);
      jianjian1.setTextureSize(64, 128);
      jianjian1.mirror = true;
      setRotation(jianjian1, 0F, 0F, 0.7853982F);
      jianjian2 = new ModelRenderer(this, 0, 114);
      jianjian2.addBox(-3.5F, -3.5F, -1.5F, 7, 7, 3);
      jianjian2.setRotationPoint(0F, 6F, 0F);
      jianjian2.setTextureSize(64, 128);
      jianjian2.mirror = true;
      setRotation(jianjian2, 0F, 0F, 0.7853982F);
      jianjian3 = new ModelRenderer(this, 29, 104);
      jianjian3.addBox(-4F, -4F, 0F, 8, 8, 2);
      jianjian3.setRotationPoint(0F, 6F, -1F);
      jianjian3.setTextureSize(64, 128);
      jianjian3.mirror = true;
      setRotation(jianjian3, 0F, 0F, 0.7853982F);
      jianjian41 = new ModelRenderer(this, 0, 0);
      jianjian41.addBox(0F, 0F, -0.5F, 2, 10, 1);
      jianjian41.setRotationPoint(-7F, 6F, 0F);
      jianjian41.setTextureSize(64, 128);
      jianjian41.mirror = true;
      setRotation(jianjian41, 0F, 0F, -0.7853982F);
      jianjian42 = new ModelRenderer(this, 9, 0);
      jianjian42.addBox(-2F, 0F, -0.5F, 2, 10, 1);
      jianjian42.setRotationPoint(7F, 6F, 0F);
      jianjian42.setTextureSize(64, 128);
      jianjian42.mirror = true;
      setRotation(jianjian42, 0F, 0F, 0.7853982F);
      jianduan1 = new ModelRenderer(this, 0, 105);
      jianduan1.addBox(-4F, 0F, -2F, 8, 2, 4);
      jianduan1.setRotationPoint(0F, -80F, 0F);
      jianduan1.setTextureSize(64, 128);
      jianduan1.mirror = true;
      setRotation(jianduan1, 0F, 0F, 0F);
      jianduan2 = new ModelRenderer(this, 0, 37);
      jianduan2.addBox(-2F, 0F, -1.5F, 4, 2, 3);
      jianduan2.setRotationPoint(0F, -78F, 0F);
      jianduan2.setTextureSize(64, 128);
      jianduan2.mirror = true;
      setRotation(jianduan2, 0F, 0F, 0F);
      jianbingg = new ModelRenderer(this, 0, 50);
      jianbingg.addBox(-1.5F, 0F, -1F, 3, 15, 2);
      jianbingg.setRotationPoint(0F, -76F, 0F);
      jianbingg.setTextureSize(64, 128);
      jianbingg.mirror = true;
      setRotation(jianbingg, 0F, 0F, 0F);
      jiange1 = new ModelRenderer(this, 0, 92);
      jiange1.addBox(-8F, 0F, -2.5F, 16, 2, 5);
      jiange1.setRotationPoint(0F, -61F, 0F);
      jiange1.setTextureSize(64, 128);
      jiange1.mirror = true;
      setRotation(jiange1, 0F, 0F, 0F);
      jiange2 = new ModelRenderer(this, 0, 76);
      jiange2.addBox(-6F, 0F, -3F, 12, 2, 6);
      jiange2.setRotationPoint(0F, -61F, 0F);
      jiange2.setTextureSize(64, 128);
      jiange2.mirror = true;
      setRotation(jiange2, 0F, 0F, 0F);
      jiansheng1 = new ModelRenderer(this, 39, 0);
      jiansheng1.addBox(-4F, 0F, -2F, 8, 65, 4);
      jiansheng1.setRotationPoint(0F, -59F, 0F);
      jiansheng1.setTextureSize(64, 128);
      jiansheng1.mirror = true;
      setRotation(jiansheng1, 0F, 0F, 0F);
      jiansheng2 = new ModelRenderer(this, 18, 0);
      jiansheng2.addBox(-5F, 0F, -1.5F, 1, 65, 3);
      jiansheng2.setRotationPoint(0F, -59F, 0F);
      jiansheng2.setTextureSize(64, 128);
      jiansheng2.mirror = true;
      setRotation(jiansheng2, 0F, 0F, 0F);
      jiansheng3 = new ModelRenderer(this, 18, 0);
      jiansheng3.addBox(0F, 0F, -1.5F, 1, 65, 3);
      jiansheng3.setRotationPoint(4F, -59F, 0F);
      jiansheng3.setTextureSize(64, 128);
      jiansheng3.mirror = true;
      setRotation(jiansheng3, 0F, 0F, 0F);
      jiansheng4 = new ModelRenderer(this, 27, 0);
      jiansheng4.addBox(0F, 0F, -1F, 1, 65, 2);
      jiansheng4.setRotationPoint(5F, -59F, 0F);
      jiansheng4.setTextureSize(64, 128);
      jiansheng4.mirror = true;
      setRotation(jiansheng4, 0F, 0F, 0F);
      jiansheng5 = new ModelRenderer(this, 27, 0);
      jiansheng5.addBox(-1F, 0F, -1F, 1, 65, 2);
      jiansheng5.setRotationPoint(-5F, -59F, 0F);
      jiansheng5.setTextureSize(64, 128);
      jiansheng5.mirror = true;
      setRotation(jiansheng5, 0F, 0F, 0F);
      jiansheng6 = new ModelRenderer(this, 34, 0);
      jiansheng6.addBox(0F, 0F, -0.5F, 1, 65, 1);
      jiansheng6.setRotationPoint(6F, -59F, 0F);
      jiansheng6.setTextureSize(64, 128);
      jiansheng6.mirror = true;
      setRotation(jiansheng6, 0F, 0F, 0F);
      jiansheng7 = new ModelRenderer(this, 34, 0);
      jiansheng7.addBox(0F, 0F, -0.5F, 1, 65, 1);
      jiansheng7.setRotationPoint(-7F, -59F, 0F);
      jiansheng7.setTextureSize(64, 128);
      jiansheng7.mirror = true;
      setRotation(jiansheng7, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    jianjian1.render(f5);
    jianjian2.render(f5);
    jianjian3.render(f5);
    jianjian41.render(f5);
    jianjian42.render(f5);
    jianduan1.render(f5);
    jianduan2.render(f5);
    jianbingg.render(f5);
    jiange1.render(f5);
    jiange2.render(f5);
    jiansheng1.render(f5);
    jiansheng2.render(f5);
    jiansheng3.render(f5);
    jiansheng4.render(f5);
    jiansheng5.render(f5);
    jiansheng6.render(f5);
    jiansheng7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void render(ItemStack is)
  {
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.6, 0.6, 0.6);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      float f5=0.0625f;
      jianjian1.render(f5);
      jianjian2.render(f5);
      jianjian3.render(f5);
      jianjian41.render(f5);
      jianjian42.render(f5);
      jianduan1.render(f5);
      jianduan2.render(f5);
      jianbingg.render(f5);
      jiange1.render(f5);
      jiange2.render(f5);
      jiansheng1.render(f5);
      jiansheng2.render(f5);
      jiansheng3.render(f5);
      jiansheng4.render(f5);
      jiansheng5.render(f5);
      jiansheng6.render(f5);
      jiansheng7.render(f5);
    }
}
