// Date: 2017/2/8 14:27:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import org.lwjgl.opengl.GL11;

public class ModelYanYueDao extends ModelBase
{
  //fields
    ModelRenderer daojian1;
    ModelRenderer daosheng5;
    ModelRenderer daosheng4;
    ModelRenderer daosheng1;
    ModelRenderer daosheng2;
    ModelRenderer daosheng3;
    ModelRenderer daojian2;
    ModelRenderer daoduan;
    ModelRenderer daoge3;
    ModelRenderer daoge2;
    ModelRenderer daoge1;
    ModelRenderer daobing;
  
  public ModelYanYueDao()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      daojian1 = new ModelRenderer(this, 0, 10);
      daojian1.addBox(-1F, -1F, -0.5F, 2, 2, 1);
      daojian1.setRotationPoint(-4.8F, -112.4F, 0F);
      daojian1.setTextureSize(64, 128);
      daojian1.mirror = true;
      setRotation(daojian1, 0F, 0F, 0.6632251F);
      daosheng5 = new ModelRenderer(this, 0, 18);
      daosheng5.addBox(-4F, -5F, -0.5F, 4, 5, 1);
      daosheng5.setRotationPoint(0.5F, -109.4F, 0F);
      daosheng5.setTextureSize(64, 128);
      daosheng5.mirror = true;
      setRotation(daosheng5, 0F, 0F, -0.8726646F);
      daosheng4 = new ModelRenderer(this, 0, 42);
      daosheng4.addBox(-2F, -19F, -0.5F, 3, 19, 1);
      daosheng4.setRotationPoint(-2F, -93.6F, 0F);
      daosheng4.setTextureSize(64, 128);
      daosheng4.mirror = true;
      setRotation(daosheng4, 0F, 0F, -0.122173F);
      daosheng1 = new ModelRenderer(this, 41, 0);
      daosheng1.addBox(-3F, 0F, -0.5F, 6, 29, 1);
      daosheng1.setRotationPoint(0F, -104F, 0F);
      daosheng1.setTextureSize(64, 128);
      daosheng1.mirror = true;
      setRotation(daosheng1, 0F, 0F, 0F);
      daosheng2 = new ModelRenderer(this, 0, 66);
      daosheng2.addBox(-6F, -16F, -0.5F, 6, 16, 1);
      daosheng2.setRotationPoint(3F, -79F, 0F);
      daosheng2.setTextureSize(64, 128);
      daosheng2.mirror = true;
      setRotation(daosheng2, 0F, 0F, -0.2617994F);
      daosheng3 = new ModelRenderer(this, 0, 30);
      daosheng3.addBox(-6F, -6F, -0.5F, 6, 6, 1);
      daosheng3.setRotationPoint(3F, -104F, 0F);
      daosheng3.setTextureSize(64, 128);
      daosheng3.mirror = true;
      setRotation(daosheng3, 0F, 0F, -0.4363323F);
      daojian2 = new ModelRenderer(this, 0, 0);
      daojian2.addBox(0F, 0F, -0.5F, 1, 2, 1);
      daojian2.setRotationPoint(-6F, -113.8F, 0F);
      daojian2.setTextureSize(64, 128);
      daojian2.mirror = true;
      setRotation(daojian2, 0F, 0F, 0F);
      daoduan = new ModelRenderer(this, 0, 99);
      daoduan.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
      daoduan.setRotationPoint(0F, 19F, 0F);
      daoduan.setTextureSize(64, 128);
      daoduan.mirror = true;
      setRotation(daoduan, 0F, 0F, 0F);
      daoge3 = new ModelRenderer(this, 0, 88);
      daoge3.addBox(0F, -5F, -1F, 3, 5, 2);
      daoge3.setRotationPoint(-0.3F, -73F, 0F);
      daoge3.setTextureSize(64, 128);
      daoge3.mirror = true;
      setRotation(daoge3, 0F, 0F, 0.2617994F);
      daoge2 = new ModelRenderer(this, 0, 109);
      daoge2.addBox(-2F, -7F, -1F, 4, 7, 2);
      daoge2.setRotationPoint(-0.3F, -73F, 0F);
      daoge2.setTextureSize(64, 128);
      daoge2.mirror = true;
      setRotation(daoge2, 0F, 0F, -0.4363323F);
      daoge1 = new ModelRenderer(this, 0, 122);
      daoge1.addBox(-3F, 0F, -2F, 6, 2, 4);
      daoge1.setRotationPoint(0F, -73F, 0F);
      daoge1.setTextureSize(64, 128);
      daoge1.mirror = true;
      setRotation(daoge1, 0F, 0F, 0F);
      daobing = new ModelRenderer(this, 56, 0);
      daobing.addBox(-1F, 0F, -1F, 2, 90, 2);
      daobing.setRotationPoint(0F, -71F, 0F);
      daobing.setTextureSize(64, 128);
      daobing.mirror = true;
      setRotation(daobing, 0F, 0F, 0F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void render(ItemStack is)
  {
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.6, 0.6, 0.6);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      float f5=0.0625f;
      daojian1.render(f5);
      daosheng5.render(f5);
      daosheng4.render(f5);
      daosheng1.render(f5);
      daosheng2.render(f5);
      daosheng3.render(f5);
      daojian2.render(f5);
      daoduan.render(f5);
      daoge3.render(f5);
      daoge2.render(f5);
      daoge1.render(f5);
      daobing.render(f5);
  }
}
