// Date: 2017/2/7 12:12:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import org.lwjgl.opengl.GL11;

public class ModelJian extends ModelBase
{
  //fields
    ModelRenderer jianbing;
    ModelRenderer jianduan;
    ModelRenderer jiange;
    ModelRenderer jiansheng1;
    ModelRenderer jiansheng21;
    ModelRenderer jiansheng22;
    ModelRenderer jianjian;
  
  public ModelJian()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      jianbing = new ModelRenderer(this, 0, 70);
      jianbing.addBox(-1F, 0F, -1F, 2, 10, 2);
      jianbing.setRotationPoint(0F, -46F, 0F);
      jianbing.setTextureSize(64, 128);
      jianbing.mirror = true;
      setRotation(jianbing, 0F, 0F, 0F);
      jianduan = new ModelRenderer(this, 0, 60);
      jianduan.addBox(-2F, 0F, -2F, 4, 4, 4);
      jianduan.setRotationPoint(0F, -50F, 0F);
      jianduan.setTextureSize(64, 128);
      jianduan.mirror = true;
      setRotation(jianduan, 0F, 0F, 0F);
      jiange = new ModelRenderer(this, 25, 0);
      jiange.addBox(-3.5F, 0F, -3F, 7, 5, 6);
      jiange.setRotationPoint(0F, -36F, 0F);
      jiange.setTextureSize(64, 128);
      jiange.mirror = true;
      setRotation(jiange, 0F, 0F, 0F);
      jiansheng1 = new ModelRenderer(this, 24, 18);
      jiansheng1.addBox(-1F, 0F, -1F, 2, 47, 2);
      jiansheng1.setRotationPoint(0F, -31F, 0F);
      jiansheng1.setTextureSize(64, 128);
      jiansheng1.mirror = true;
      setRotation(jiansheng1, 0F, 0F, 0F);
      jiansheng21 = new ModelRenderer(this, 12, 0);
      jiansheng21.addBox(-2F, 0F, -1.5F, 2, 48, 3);
      jiansheng21.setRotationPoint(3F, -31F, 0F);
      jiansheng21.setTextureSize(64, 128);
      jiansheng21.mirror = true;
      setRotation(jiansheng21, 0F, 0F, 0.0174533F);
      jiansheng22 = new ModelRenderer(this, 0, 0);
      jiansheng22.addBox(0F, 0F, -1.5F, 2, 48, 3);
      jiansheng22.setRotationPoint(-3F, -31F, 0F);
      jiansheng22.setTextureSize(64, 128);
      jiansheng22.mirror = true;
      setRotation(jiansheng22, 0F, 0F, -0.0174533F);
      jianjian = new ModelRenderer(this, 0, 52);
      jianjian.addBox(-1.5F, -1.5F, 0F, 3, 3, 3);
      jianjian.setRotationPoint(0F, 17F, -1.5F);
      jianjian.setTextureSize(64, 128);
      jianjian.mirror = true;
      setRotation(jianjian, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    jianbing.render(f5);
    jianduan.render(f5);
    jiange.render(f5);
    jiansheng1.render(f5);
    jiansheng21.render(f5);
    jiansheng22.render(f5);
    jianjian.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void render(ItemStack is)
  {
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.6, 0.6, 0.6);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      float f5=0.0625f;
      jianbing.render(f5);
      jianduan.render(f5);
      jiange.render(f5);
      //body
      jiansheng1.render(f5);
      jiansheng21.render(f5);
      jiansheng22.render(f5);
      jianjian.render(f5);
    }
}
