// Date: 2017/2/7 15:03:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import org.lwjgl.opengl.GL11;

import com.Jackiecrazi.taoism.client.RenderHalper;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class ModelHuanShouDao extends ModelBase
{
	//fields
	ModelRenderer daijian1;
	ModelRenderer daojian2;
	ModelRenderer daojian3;
	ModelRenderer daijian4;
	ModelRenderer daojian5;
	ModelRenderer daojian6;
	ModelRenderer daojian7;
	ModelRenderer daosheng1;
	ModelRenderer daosheng2;
	ModelRenderer huan6;
	ModelRenderer huan5;
	ModelRenderer huan1;
	ModelRenderer huan3;
	ModelRenderer huan4;
	ModelRenderer huan7;
	ModelRenderer huan8;
	ModelRenderer daobingg;
	ModelRenderer daobuan;
	ModelRenderer daoduan1;
	ModelRenderer daoduan2;

	public ModelHuanShouDao()
	{
		textureWidth = 64;
		textureHeight = 128;

		daijian1 = new ModelRenderer(this, 0, 70);
		daijian1.addBox(-2F, 0F, -0.5F, 2, 6, 1);
		daijian1.setRotationPoint(2.5F, 18F, 0F);
		daijian1.setTextureSize(64, 128);
		daijian1.mirror = true;
		setRotation(daijian1, 0F, 0F, 0.5410521F);
		daojian2 = new ModelRenderer(this, 0, 79);
		daojian2.addBox(-1F, 0F, -1F, 1, 6, 2);
		daojian2.setRotationPoint(-1.5F, 16F, 0F);
		daojian2.setTextureSize(64, 128);
		daojian2.mirror = true;
		setRotation(daojian2, 0F, 0F, 0F);
		daojian3 = new ModelRenderer(this, 0, 89);
		daojian3.addBox(0F, 0F, -1F, 2, 6, 2);
		daojian3.setRotationPoint(-2.5F, 13.5F, 0F);
		daojian3.setTextureSize(64, 128);
		daojian3.mirror = true;
		setRotation(daojian3, 0F, 0F, 0F);
		daijian4 = new ModelRenderer(this, 8, 70);
		daijian4.addBox(-3F, 0F, -0.5F, 3, 4, 1);
		daijian4.setRotationPoint(2.1F, 18.4F, 0F);
		daijian4.setTextureSize(64, 128);
		daijian4.mirror = true;
		setRotation(daijian4, 0F, 0F, 0.5410521F);
		daojian5 = new ModelRenderer(this, 8, 79);
		daojian5.addBox(-1F, -1F, -0.5F, 2, 2, 1);
		daojian5.setRotationPoint(-1.5F, 22F, 0F);
		daojian5.setTextureSize(64, 128);
		daojian5.mirror = true;
		setRotation(daojian5, 0F, 0F, 0F);
		daojian6 = new ModelRenderer(this, 11, 89);
		daojian6.addBox(-1F, -1F, -0.5F, 1, 3, 1);
		daojian6.setRotationPoint(-1.5F, 22.2F, 0F);
		daojian6.setTextureSize(64, 128);
		daojian6.mirror = true;
		setRotation(daojian6, 0F, 0F, 0F);
		daojian7 = new ModelRenderer(this, 17, 89);
		daojian7.addBox(-1F, 0F, -0.5F, 1, 8, 1);
		daojian7.setRotationPoint(2.5F, 18F, 0F);
		daojian7.setTextureSize(64, 128);
		daojian7.mirror = true;
		setRotation(daojian7, 0F, 0F, 0.5410521F);
		daosheng1 = new ModelRenderer(this, 0, 0);
		daosheng1.addBox(-1.5F, 0F, -1F, 3, 64, 2);
		daosheng1.setRotationPoint(-1F, -46F, 0F);
		daosheng1.setTextureSize(64, 128);
		daosheng1.mirror = true;
		setRotation(daosheng1, 0F, 0F, 0F);
		daosheng2 = new ModelRenderer(this, 12, 0);
		daosheng2.addBox(-1F, 0F, -0.5F, 2, 64, 1);
		daosheng2.setRotationPoint(1.5F, -46F, 0F);
		daosheng2.setTextureSize(64, 128);
		daosheng2.mirror = true;
		setRotation(daosheng2, 0F, 0F, 0F);
		huan6 = new ModelRenderer(this, 20, 5);
		huan6.addBox(-1.5F, -1F, -0.5F, 3, 1, 1);
		huan6.setRotationPoint(-1.2F, -65F, 0F);
		huan6.setTextureSize(64, 128);
		huan6.mirror = true;
		setRotation(huan6, 0F, 0F, -2.268928F);
		huan6.mirror = false;
		huan5 = new ModelRenderer(this, 20, 5);
		huan5.addBox(-1.5F, 0F, -0.5F, 3, 1, 1);
		huan5.setRotationPoint(1.2F, -65F, 0F);
		huan5.setTextureSize(64, 128);
		huan5.mirror = true;
		setRotation(huan5, 0F, 0F, -0.8726646F);
		huan1 = new ModelRenderer(this, 20, 0);
		huan1.addBox(-1F, 0F, -0.5F, 2, 1, 1);
		huan1.setRotationPoint(0F, -69.8F, 0F);
		huan1.setTextureSize(64, 128);
		huan1.mirror = true;
		setRotation(huan1, 0F, 0F, 0F);
		huan3 = new ModelRenderer(this, 20, 0);
		huan3.addBox(-1F, 0F, -0.5F, 2, 1, 1);
		huan3.setRotationPoint(-2F, -66.5F, 0F);
		huan3.setTextureSize(64, 128);
		huan3.mirror = true;
		setRotation(huan3, 0F, 0F, 1.570796F);
		huan4 = new ModelRenderer(this, 20, 0);
		huan4.addBox(-1F, 0F, -0.5F, 2, 1, 1);
		huan4.setRotationPoint(1.95F, -66.5F, 0F);
		huan4.setTextureSize(64, 128);
		huan4.mirror = true;
		setRotation(huan4, 0F, 0F, -1.570796F);
		huan7 = new ModelRenderer(this, 20, 5);
		huan7.addBox(-1.5F, 0F, -0.5F, 3, 1, 1);
		huan7.setRotationPoint(1.2F, -68F, 0F);
		huan7.setTextureSize(64, 128);
		huan7.mirror = true;
		setRotation(huan7, 0F, 0F, -2.268928F);
		huan8 = new ModelRenderer(this, 20, 5);
		huan8.addBox(-1.5F, -1F, -0.5F, 3, 1, 1);
		huan8.setRotationPoint(-1.2F, -68F, 0F);
		huan8.setTextureSize(64, 128);
		huan8.mirror = true;
		setRotation(huan8, 0F, 0F, -0.8726646F);
		daobingg = new ModelRenderer(this, 20, 16);
		daobingg.addBox(-1.5F, 0F, -1F, 3, 14, 2);
		daobingg.setRotationPoint(0F, -62F, 0F);
		daobingg.setTextureSize(64, 128);
		daobingg.mirror = true;
		setRotation(daobingg, 0F, 0F, 0F);
		daobuan = new ModelRenderer(this, 20, 9);
		daobuan.addBox(-2F, 0F, -1.5F, 4, 2, 3);
		daobuan.setRotationPoint(0F, -64F, 0F);
		daobuan.setTextureSize(64, 128);
		daobuan.mirror = true;
		setRotation(daobuan, 0F, 0F, 0F);
		daoduan1 = new ModelRenderer(this, 20, 34);
		daoduan1.addBox(-3F, 0F, -1.5F, 6, 2, 3);
		daoduan1.setRotationPoint(0F, -48F, 0F);
		daoduan1.setTextureSize(64, 128);
		daoduan1.mirror = true;
		setRotation(daoduan1, 0F, 0F, 0F);
		daoduan2 = new ModelRenderer(this, 20, 41);
		daoduan2.addBox(-2F, 0F, -2F, 4, 2, 4);
		daoduan2.setRotationPoint(0F, -48F, 0F);
		daoduan2.setTextureSize(64, 128);
		daoduan2.mirror = true;
		setRotation(daoduan2, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		daijian1.render(f5);
		daojian2.render(f5);
		daojian3.render(f5);
		daijian4.render(f5);
		daojian5.render(f5);
		daojian6.render(f5);
		daojian7.render(f5);
		daosheng1.render(f5);
		daosheng2.render(f5);
		huan6.render(f5);
		huan5.render(f5);
		huan1.render(f5);
		huan3.render(f5);
		huan4.render(f5);
		huan7.render(f5);
		huan8.render(f5);
		daobingg.render(f5);
		daobuan.render(f5);
		daoduan1.render(f5);
		daoduan2.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	public void render(ItemStack is,String edge,String body, String loop, String handle,String pommel, String guard)
	{
		if (RenderManager.instance.renderEngine == null) return;
		Item wand = is.getItem();
		EntityPlayer player = Minecraft.getMinecraft().thePlayer;
		GL11.glScaled(0.6, 0.6, 0.6);
		GL11.glRotated(30, 0, 0, 1);
		GL11.glTranslated(1.2, 2.8d, 0);
		float f5=0.0625f;
		RenderHalper.bindMatTex(edge);
		daijian1.render(f5);
		daosheng2.render(f5);
		daijian4.render(f5);
		daojian5.render(f5);
		daojian6.render(f5);
		daojian7.render(f5);
		RenderHalper.bindMatTex(body);
		daosheng1.render(f5);//body
		daojian2.render(f5);//body
		daojian3.render(f5);//body

		RenderHalper.bindMatTex(loop);
		huan6.render(f5);
		huan5.render(f5);
		huan1.render(f5);
		huan3.render(f5);
		huan4.render(f5);
		huan7.render(f5);
		huan8.render(f5);
		RenderHalper.bindMatTex(handle);
		daobingg.render(f5);
		RenderHalper.bindMatTex(pommel);
		daobuan.render(f5);
		RenderHalper.bindMatTex(guard);
		daoduan1.render(f5);
		daoduan2.render(f5);
	}
}
