// Date: 2017/2/6 23:28:29
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import org.lwjgl.opengl.GL11;

import com.Jackiecrazi.taoism.client.RenderHalper;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class ModelTrident  extends ModelBase
{
  //fields
    ModelRenderer chage1;
    ModelRenderer chage2;
    ModelRenderer chage32;
    ModelRenderer chage31;
    ModelRenderer chage4;
    ModelRenderer chaduan;
    ModelRenderer chabingg;
    ModelRenderer chajian1;
    ModelRenderer chajian11;
    ModelRenderer chajian2;
    ModelRenderer chajian21;
    ModelRenderer chajian3;
    ModelRenderer chajian31;
  
  public ModelTrident ()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      chage1 = new ModelRenderer(this, 0, 57);
      chage1.addBox(-3F, 0F, -2F, 6, 3, 4);
      chage1.setRotationPoint(0F, -45F, 0F);
      chage1.setTextureSize(128, 64);
      chage1.mirror = true;
      setRotation(chage1, 0F, 0F, 0F);
      chage2 = new ModelRenderer(this, 0, 45);
      chage2.addBox(-4F, 0F, -2F, 8, 4, 4);
      chage2.setRotationPoint(0F, -49F, 0F);
      chage2.setTextureSize(128, 64);
      chage2.mirror = true;
      setRotation(chage2, 0F, 0F, 0F);
      chage32 = new ModelRenderer(this, 0, 31);
      chage32.addBox(0F, -9F, -2F, 4, 9, 4);
      chage32.setRotationPoint(-4F, -45F, 0F);
      chage32.setTextureSize(128, 64);
      chage32.mirror = true;
      setRotation(chage32, 0F, 0F, -0.5235988F);
      chage31 = new ModelRenderer(this, 0, 31);
      chage31.addBox(-4F, -9F, -2F, 4, 9, 4);
      chage31.setRotationPoint(4F, -45F, 0F);
      chage31.setTextureSize(128, 64);
      chage31.mirror = true;
      setRotation(chage31, 0F, 0F, 0.5235988F);
      chage4 = new ModelRenderer(this, 0, 20);
      chage4.addBox(-3F, -3F, 0F, 6, 6, 4);
      chage4.setRotationPoint(0F, -53F, -2F);
      chage4.setTextureSize(128, 64);
      chage4.mirror = true;
      setRotation(chage4, 0F, 0F, 0.7853982F);
      chaduan = new ModelRenderer(this, 50, 0);
      chaduan.addBox(-1.5F, 0F, -1.5F, 3, 4, 3);
      chaduan.setRotationPoint(0F, 20F, 0F);
      chaduan.setTextureSize(128, 64);
      chaduan.mirror = true;
      setRotation(chaduan, 0F, 0F, 0F);
      chabingg = new ModelRenderer(this, 40, 0);
      chabingg.addBox(-1F, 0F, -1F, 2, 62, 2);
      chabingg.setRotationPoint(0F, -42F, 0F);
      chabingg.setTextureSize(128, 64);
      chabingg.mirror = true;
      setRotation(chabingg, 0F, 0F, 0F);
      chajian1 = new ModelRenderer(this, 0, 0);
      chajian1.addBox(-1.5F, -11F, -1F, 3, 11, 2);
      chajian1.setRotationPoint(6.5F, -53F, 0F);
      chajian1.setTextureSize(128, 64);
      chajian1.mirror = true;
      setRotation(chajian1, 0F, 0F, 0F);
      chajian11 = new ModelRenderer(this, 15, 0);
      chajian11.addBox(-1F, -1F, 0F, 2, 2, 2);
      chajian11.setRotationPoint(6.5F, -64F, -1F);
      chajian11.setTextureSize(128, 64);
      chajian11.mirror = true;
      setRotation(chajian11, 0F, 0F, 0.7853982F);
      chajian2 = new ModelRenderer(this, 0, 0);
      chajian2.addBox(-1.5F, -11F, -1F, 3, 11, 2);
      chajian2.setRotationPoint(-6.5F, -53F, 0F);
      chajian2.setTextureSize(128, 64);
      chajian2.mirror = true;
      setRotation(chajian2, 0F, 0F, 0F);
      chajian21 = new ModelRenderer(this, 15, 0);
      chajian21.addBox(-1F, -1F, 0F, 2, 2, 2);
      chajian21.setRotationPoint(-6.5F, -64F, -1F);
      chajian21.setTextureSize(128, 64);
      chajian21.mirror = true;
      setRotation(chajian21, 0F, 0F, 0.7853982F);
      chajian3 = new ModelRenderer(this, 25, 0);
      chajian3.addBox(-2F, -16F, -1F, 4, 16, 2);
      chajian3.setRotationPoint(0F, -54F, 0F);
      chajian3.setTextureSize(128, 64);
      chajian3.mirror = true;
      setRotation(chajian3, 0F, 0F, 0F);
      chajian31 = new ModelRenderer(this, 0, 14);
      chajian31.addBox(-1.5F, -1.5F, 0F, 3, 3, 2);
      chajian31.setRotationPoint(0F, -70F, -1F);
      chajian31.setTextureSize(128, 64);
      chajian31.mirror = true;
      setRotation(chajian31, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    chage1.render(f5);
    chage2.render(f5);
    chage32.render(f5);
    chage31.render(f5);
    chage4.render(f5);
    chaduan.render(f5);
    chabingg.render(f5);
    chajian1.render(f5);
    chajian11.render(f5);
    chajian2.render(f5);
    chajian21.render(f5);
    chajian3.render(f5);
    chajian31.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,e);
  }
  public void render(ItemStack is,String hilt,String body,String pommel,String tip)
  {
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.6, 0.6, 0.6);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      float f5=0.0625f;
      RenderHalper.bindMatTex(hilt);
      chage1.render(f5);
      chage2.render(f5);
      chage32.render(f5);
      chage31.render(f5);
      chage4.render(f5);//hilt
      RenderHalper.bindMatTex(pommel);
      chaduan.render(f5);//pommel
      RenderHalper.bindMatTex(body);
      chabingg.render(f5);//body
      RenderHalper.bindMatTex(tip);
      chajian1.render(f5);
      chajian11.render(f5);
      chajian2.render(f5);
      chajian21.render(f5);
      chajian3.render(f5);
      chajian31.render(f5);//tip
  }
}
