// Date: 2017/2/6 21:17:33
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import org.lwjgl.opengl.GL11;

import com.Jackiecrazi.taoism.api.NeedyLittleThings;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class ModelSword extends ModelBase
{
  //fields
    ModelRenderer jianduan;
    ModelRenderer jianbing;
    ModelRenderer jiange;
    ModelRenderer jiansheng;
    ModelRenderer jianren1;
    ModelRenderer jianren2;
    ModelRenderer jianjian12;
    ModelRenderer jianjian11;
    ModelRenderer jianjian13;
    ModelRenderer jianjian22;
    ModelRenderer jianjian21;
    ModelRenderer jianjian23;
    ModelRenderer jianjian24;
  
  public ModelSword()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      jianduan = new ModelRenderer(this, 47, 0);
      jianduan.addBox(-2.5F, -1F, -1.5F, 5, 1, 3);
      jianduan.setRotationPoint(0F, -55F, 0F);
      jianduan.setTextureSize(128, 64);
      jianduan.mirror = true;
      setRotation(jianduan, 0F, 0F, 0F);
      jianbing = new ModelRenderer(this, 38, 0);
      jianbing.addBox(-1F, 0F, -1F, 2, 10, 2);
      jianbing.setRotationPoint(0F, -55F, 0F);
      jianbing.setTextureSize(128, 64);
      jianbing.mirror = true;
      setRotation(jianbing, 0F, 0F, 0F);
      jiange = new ModelRenderer(this, 13, 0);
      jiange.addBox(-4F, 0F, -2F, 8, 2, 4);
      jiange.setRotationPoint(0F, -45F, 0F);
      jiange.setTextureSize(128, 64);
      jiange.mirror = true;
      setRotation(jiange, 0F, 0F, 0F);
      jiansheng = new ModelRenderer(this, 0, 0);
      jiansheng.addBox(-2F, 0F, -1F, 4, 36, 2);
      jiansheng.setRotationPoint(0F, -43F, 0F);
      jiansheng.setTextureSize(128, 64);
      jiansheng.mirror = true;
      setRotation(jiansheng, 0F, 0F, 0F);
      jianren1 = new ModelRenderer(this, 15, 9);
      jianren1.addBox(-1F, 0F, -0.5F, 1, 36, 1);
      jianren1.setRotationPoint(-2F, -43F, 0F);
      jianren1.setTextureSize(128, 64);
      jianren1.mirror = true;
      setRotation(jianren1, 0F, 0F, 0F);
      jianren2 = new ModelRenderer(this, 15, 9);
      jianren2.addBox(0F, 0F, -0.5F, 1, 36, 1);
      jianren2.setRotationPoint(2F, -43F, 0F);
      jianren2.setTextureSize(128, 64);
      jianren2.mirror = true;
      setRotation(jianren2, 0F, 0F, 0F);
      jianjian12 = new ModelRenderer(this, 24, 11);
      jianjian12.addBox(0F, 0F, -1F, 2, 3, 2);
      jianjian12.setRotationPoint(-2F, -7F, 0F);
      jianjian12.setTextureSize(128, 64);
      jianjian12.mirror = true;
      setRotation(jianjian12, 0F, 0F, -0.4363323F);
      jianjian11 = new ModelRenderer(this, 24, 11);
      jianjian11.addBox(-2F, 0F, -1F, 2, 3, 2);
      jianjian11.setRotationPoint(2F, -7F, 0F);
      jianjian11.setTextureSize(128, 64);
      jianjian11.mirror = true;
      setRotation(jianjian11, 0F, 0F, 0.4363323F);
      jianjian13 = new ModelRenderer(this, 24, 16);
      jianjian13.addBox(-1F, 0F, -1F, 2, 3, 2);
      jianjian13.setRotationPoint(0F, -7F, 0F);
      jianjian13.setTextureSize(128, 64);
      jianjian13.mirror = true;
      setRotation(jianjian13, 0F, 0F, 0F);
      jianjian22 = new ModelRenderer(this, 24, 26);
      jianjian22.addBox(-1F, 0F, -0.5F, 1, 6, 1);
      jianjian22.setRotationPoint(3F, -7F, 0F);
      jianjian22.setTextureSize(128, 64);
      jianjian22.mirror = true;
      setRotation(jianjian22, 0F, 0F, 0.4363323F);
      jianjian21 = new ModelRenderer(this, 24, 26);
      jianjian21.addBox(0F, 0F, -0.5F, 1, 6, 1);
      jianjian21.setRotationPoint(-3F, -7F, 0F);
      jianjian21.setTextureSize(128, 64);
      jianjian21.mirror = true;
      setRotation(jianjian21, 0F, 0F, -0.4363323F);
      jianjian23 = new ModelRenderer(this, 24, 51);
      jianjian23.addBox(-1F, 0F, -0.5F, 2, 2, 1);
      jianjian23.setRotationPoint(0F, -4.7F, 0F);
      jianjian23.setTextureSize(128, 64);
      jianjian23.mirror = true;
      setRotation(jianjian23, 0F, 0F, 0F);
      jianjian24 = new ModelRenderer(this, 24, 38);
      jianjian24.addBox(-1F, -1F, 0F, 1, 1, 1);
      jianjian24.setRotationPoint(0F, -1.25F, -0.5F);
      jianjian24.setTextureSize(128, 64);
      jianjian24.mirror = true;
      setRotation(jianjian24, 0F, 0F, 0.7853982F);
      
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    jianduan.render(f5);
    jianbing.render(f5);
    jiange.render(f5);
    jiansheng.render(f5);
    jianren1.render(f5);
    jianren2.render(f5);
    jianjian12.render(f5);
    jianjian11.render(f5);
    jianjian13.render(f5);
    jianjian22.render(f5);
    jianjian21.render(f5);
    jianjian23.render(f5);
    jianjian24.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  @Override
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity nope)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,nope);
  }
  /**
   * you gotta come back some time and add all the textures
   * @param is
   */
  public void render(ItemStack is)
  {
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.6, 0.6, 0.6);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      //GL11.glRotated(180, 0d, 0d, 1d);
      float f5=0.0625f;
      jianduan.render(f5);
      jianbing.render(f5);
      jiange.render(f5);
      jiansheng.render(f5);
      jianren1.render(f5);
      jianren2.render(f5);
      jianjian12.render(f5);
      jianjian11.render(f5);
      jianjian13.render(f5);
      jianjian22.render(f5);
      jianjian21.render(f5);
      jianjian23.render(f5);
      jianjian24.render(f5);
  }
}
