// Date: 2017/2/7 10:45:03
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;

import org.lwjgl.opengl.GL11;

import cpw.mods.fml.client.FMLClientHandler;

public class ModelLance  extends ModelBase
{
  //fields
    ModelRenderer qiangge;
    ModelRenderer qiangbing;
    ModelRenderer qiangduan1;
    ModelRenderer qiangge21;
    ModelRenderer qiangge22;
    ModelRenderer qiangjian1;
    ModelRenderer qiangjian21;
    ModelRenderer qiangjian22;
    ModelRenderer qiangjian3;
  
  public ModelLance ()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      qiangge = new ModelRenderer(this, 20, 7);
      qiangge.addBox(-2F, 0F, -2F, 4, 4, 4);
      qiangge.setRotationPoint(0F, -64F, 0F);
      qiangge.setTextureSize(64, 128);
      qiangge.mirror = true;
      setRotation(qiangge, 0F, 0F, 0F);
      qiangbing = new ModelRenderer(this, 0, 0);
      qiangbing.addBox(-1F, 0F, -1F, 2, 80, 2);
      qiangbing.setRotationPoint(0F, -60F, 0F);
      qiangbing.setTextureSize(64, 128);
      qiangbing.mirror = true;
      setRotation(qiangbing, 0F, 0F, 0F);
      qiangduan1 = new ModelRenderer(this, 20, 0);
      qiangduan1.addBox(-1.5F, 0F, 0F, 3, 3, 3);
      qiangduan1.setRotationPoint(0F, 18F, 0F);
      qiangduan1.setTextureSize(64, 128);
      qiangduan1.mirror = true;
      setRotation(qiangduan1, -0.7853982F, 0F, 0F);
      qiangge21 = new ModelRenderer(this, 20, 20);
      qiangge21.addBox(-3F, -3F, -1.5F, 3, 3, 3);
      qiangge21.setRotationPoint(2F, -62F, 0F);
      qiangge21.setTextureSize(64, 128);
      qiangge21.mirror = true;
      setRotation(qiangge21, 0F, 0F, 0.5235988F);
      qiangge22 = new ModelRenderer(this, 20, 20);
      qiangge22.addBox(0F, -3F, -1.5F, 3, 3, 3);
      qiangge22.setRotationPoint(-2F, -62F, 0F);
      qiangge22.setTextureSize(64, 128);
      qiangge22.mirror = true;
      setRotation(qiangge22, 0F, 0F, -0.5235988F);
      qiangjian1 = new ModelRenderer(this, 9, 20);
      qiangjian1.addBox(-2F, 0F, -0.5F, 4, 6, 1);
      qiangjian1.setRotationPoint(0F, -70F, 0F);
      qiangjian1.setTextureSize(64, 128);
      qiangjian1.mirror = true;
      setRotation(qiangjian1, 0F, 0F, 0F);
      qiangjian21 = new ModelRenderer(this, 9, 10);
      qiangjian21.addBox(-2F, -6F, -0.5F, 2, 6, 1);
      qiangjian21.setRotationPoint(2F, -70F, 0F);
      qiangjian21.setTextureSize(64, 128);
      qiangjian21.mirror = true;
      setRotation(qiangjian21, 0F, 0F, -0.1064651F);
      qiangjian22 = new ModelRenderer(this, 9, 10);
      qiangjian22.addBox(0F, -6F, -0.5F, 2, 6, 1);
      qiangjian22.setRotationPoint(-2F, -70F, 0F);
      qiangjian22.setTextureSize(64, 128);
      qiangjian22.mirror = true;
      setRotation(qiangjian22, 0F, 0F, 0.1064651F);
      qiangjian3 = new ModelRenderer(this, 9, 0);
      qiangjian3.addBox(-1F, -1F, 0F, 2, 2, 1);
      qiangjian3.setRotationPoint(0F, -76F, -0.5F);
      qiangjian3.setTextureSize(64, 128);
      qiangjian3.mirror = true;
      setRotation(qiangjian3, 0F, 0F, 0.7853982F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    qiangge.render(f5);
    qiangbing.render(f5);
    qiangduan1.render(f5);
    qiangge21.render(f5);
    qiangge22.render(f5);
    qiangjian1.render(f5);
    qiangjian21.render(f5);
    qiangjian22.render(f5);
    qiangjian3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void render(ItemStack is,String guardName,String shaftName,String pommelName,String tipName)
  {
	  
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.6, 0.6, 0.6);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      float f5=0.0625f;
      //guard
      FMLClientHandler.instance().getClient().renderEngine
		.bindTexture(new ResourceLocation("taoism:textures/items/weapons/"+guardName+".png"));
      qiangge.render(f5);
      qiangge21.render(f5);
      qiangge22.render(f5);
      //shaft
      FMLClientHandler.instance().getClient().renderEngine
		.bindTexture(new ResourceLocation("taoism:textures/items/weapons/"+shaftName+".png"));
      qiangbing.render(f5);
      //pommel
      FMLClientHandler.instance().getClient().renderEngine
		.bindTexture(new ResourceLocation("taoism:textures/items/weapons/"+pommelName+".png"));
      qiangduan1.render(f5);
      //tip
      FMLClientHandler.instance().getClient().renderEngine
		.bindTexture(new ResourceLocation("taoism:textures/items/weapons/"+tipName+".png"));
      
      qiangjian1.render(f5);
      qiangjian21.render(f5);
      qiangjian22.render(f5);
      qiangjian3.render(f5);
    }
}
