// Date: 2017/2/7 23:41:41
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import org.lwjgl.opengl.GL11;

import com.Jackiecrazi.taoism.client.RenderHalper;

public class ModelEMeiCi extends ModelBase
{
  //fields
    ModelRenderer xiajian42;
    ModelRenderer xiajian41;
    ModelRenderer xiajian32;
    ModelRenderer xiajian31;
    ModelRenderer xiajian22;
    ModelRenderer xiajian21;
    ModelRenderer xiajian11;
    ModelRenderer xiajian12;
    ModelRenderer shangjian11;
    ModelRenderer shangjian41;
    ModelRenderer shangjian21;
    ModelRenderer shangjian12;
    ModelRenderer shangjian22;
    ModelRenderer shangjian32;
    ModelRenderer shangjian42;
    ModelRenderer shangjian31;
    ModelRenderer cibing;
    ModelRenderer cige2;
    ModelRenderer cige1;
  
  public ModelEMeiCi()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      xiajian42 = new ModelRenderer(this, 0, 0);
      xiajian42.addBox(-0.5F, 0F, -0.5F, 1, 10, 1);
      xiajian42.setRotationPoint(0F, 6F, 0F);
      xiajian42.setTextureSize(64, 128);
      xiajian42.mirror = true;
      setRotation(xiajian42, 0F, 0.7853982F, 0F);
      xiajian41 = new ModelRenderer(this, 0, 0);
      xiajian41.addBox(-0.5F, 0F, -0.5F, 1, 10, 1);
      xiajian41.setRotationPoint(0F, 6F, 0F);
      xiajian41.setTextureSize(64, 128);
      xiajian41.mirror = true;
      setRotation(xiajian41, 0F, 0F, 0F);
      xiajian32 = new ModelRenderer(this, 22, 0);
      xiajian32.addBox(-1F, 0F, -1F, 2, 25, 2);
      xiajian32.setRotationPoint(0F, -19F, 0F);
      xiajian32.setTextureSize(64, 128);
      xiajian32.mirror = true;
      setRotation(xiajian32, 0F, 0.7853982F, 0F);
      xiajian31 = new ModelRenderer(this, 22, 0);
      xiajian31.addBox(-1F, 0F, -1F, 2, 25, 2);
      xiajian31.setRotationPoint(0F, -19F, 0F);
      xiajian31.setTextureSize(64, 128);
      xiajian31.mirror = true;
      setRotation(xiajian31, 0F, 0F, 0F);
      xiajian22 = new ModelRenderer(this, 0, 53);
      xiajian22.addBox(-2F, 0F, -2F, 4, 20, 4);
      xiajian22.setRotationPoint(0F, -39F, 0F);
      xiajian22.setTextureSize(64, 128);
      xiajian22.mirror = true;
      setRotation(xiajian22, 0F, 0.7853982F, 0F);
      xiajian21 = new ModelRenderer(this, 0, 53);
      xiajian21.addBox(-2F, 0F, -2F, 4, 20, 4);
      xiajian21.setRotationPoint(0F, -39F, 0F);
      xiajian21.setTextureSize(64, 128);
      xiajian21.mirror = true;
      setRotation(xiajian21, 0F, 0F, 0F);
      xiajian11 = new ModelRenderer(this, 0, 30);
      xiajian11.addBox(-3F, 0F, -3F, 6, 15, 6);
      xiajian11.setRotationPoint(0F, -54F, 0F);
      xiajian11.setTextureSize(64, 128);
      xiajian11.mirror = true;
      setRotation(xiajian11, 0F, 0F, 0F);
      xiajian12 = new ModelRenderer(this, 0, 30);
      xiajian12.addBox(-3F, 0F, -3F, 6, 15, 6);
      xiajian12.setRotationPoint(0F, -54F, 0F);
      xiajian12.setTextureSize(64, 128);
      xiajian12.mirror = true;
      setRotation(xiajian12, 0F, 0.7853982F, 0F);
      shangjian11 = new ModelRenderer(this, 0, 30);
      shangjian11.addBox(-3F, 0F, -3F, 6, 15, 6);
      shangjian11.setRotationPoint(0F, -130F, 0F);
      shangjian11.setTextureSize(64, 128);
      shangjian11.mirror = true;
      setRotation(shangjian11, 0F, 0F, 0F);
      shangjian41 = new ModelRenderer(this, 0, 0);
      shangjian41.addBox(-0.5F, 0F, -0.5F, 1, 10, 1);
      shangjian41.setRotationPoint(0F, -185F, 0F);
      shangjian41.setTextureSize(64, 128);
      shangjian41.mirror = true;
      setRotation(shangjian41, 0F, 0F, 0F);
      shangjian21 = new ModelRenderer(this, 0, 53);
      shangjian21.addBox(-2F, 0F, -2F, 4, 20, 4);
      shangjian21.setRotationPoint(0F, -150F, 0F);
      shangjian21.setTextureSize(64, 128);
      shangjian21.mirror = true;
      setRotation(shangjian21, 0F, 0F, 0F);
      shangjian12 = new ModelRenderer(this, 0, 30);
      shangjian12.addBox(-3F, 0F, -3F, 6, 15, 6);
      shangjian12.setRotationPoint(0F, -130F, 0F);
      shangjian12.setTextureSize(64, 128);
      shangjian12.mirror = true;
      setRotation(shangjian12, 0F, 0.7853982F, 0F);
      shangjian22 = new ModelRenderer(this, 0, 53);
      shangjian22.addBox(-2F, 0F, -2F, 4, 20, 4);
      shangjian22.setRotationPoint(0F, -150F, 0F);
      shangjian22.setTextureSize(64, 128);
      shangjian22.mirror = true;
      setRotation(shangjian22, 0F, 0.7853982F, 0F);
      shangjian32 = new ModelRenderer(this, 22, 0);
      shangjian32.addBox(-1F, 0F, -1F, 2, 25, 2);
      shangjian32.setRotationPoint(0F, -175F, 0F);
      shangjian32.setTextureSize(64, 128);
      shangjian32.mirror = true;
      setRotation(shangjian32, 0F, 0.7853982F, 0F);
      shangjian42 = new ModelRenderer(this, 0, 0);
      shangjian42.addBox(-0.5F, 0F, -0.5F, 1, 10, 1);
      shangjian42.setRotationPoint(0F, -185F, 0F);
      shangjian42.setTextureSize(64, 128);
      shangjian42.mirror = true;
      setRotation(shangjian42, 0F, 0.7853982F, 0F);
      shangjian31 = new ModelRenderer(this, 22, 0);
      shangjian31.addBox(-1F, 0F, -1F, 2, 25, 2);
      shangjian31.setRotationPoint(0F, -175F, 0F);
      shangjian31.setTextureSize(64, 128);
      shangjian31.mirror = true;
      setRotation(shangjian31, 0F, 0F, 0F);
      cibing = new ModelRenderer(this, 0, 79);
      cibing.addBox(-2F, 0F, -2F, 4, 45, 4);
      cibing.setRotationPoint(0F, -107F, 0F);
      cibing.setTextureSize(64, 128);
      cibing.mirror = true;
      setRotation(cibing, 0F, 0F, 0F);
      cige2 = new ModelRenderer(this, 36, 0);
      cige2.addBox(-3.5F, 0F, -3.5F, 7, 8, 7);
      cige2.setRotationPoint(0F, -62F, 0F);
      cige2.setTextureSize(64, 128);
      cige2.mirror = true;
      setRotation(cige2, 0F, 0F, 0F);
      cige1 = new ModelRenderer(this, 36, 0);
      cige1.addBox(-3.5F, 0F, -3.5F, 7, 8, 7);
      cige1.setRotationPoint(0F, -115F, 0F);
      cige1.setTextureSize(64, 128);
      cige1.mirror = true;
      setRotation(cige1, 0F, 0F, 0F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void render(ItemStack is,String tip,String handle)
  {
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.1, 0.1, 0.1);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      float f5=0.0625f;
      RenderHalper.bindMatTex(tip);
      xiajian42.render(f5);
      xiajian41.render(f5);
      xiajian32.render(f5);
      xiajian31.render(f5);
      xiajian22.render(f5);
      xiajian21.render(f5);
      xiajian11.render(f5);
      xiajian12.render(f5);
      shangjian11.render(f5);
      shangjian41.render(f5);
      shangjian21.render(f5);
      shangjian12.render(f5);
      shangjian22.render(f5);
      shangjian32.render(f5);
      shangjian42.render(f5);
      shangjian31.render(f5);
      RenderHalper.bindMatTex(handle);
      cibing.render(f5);
      cige2.render(f5);
      cige1.render(f5);
  }

}
