// Date: 2017/2/8 17:56:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.items.weapons.fu;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import org.lwjgl.opengl.GL11;

public class ModelFuOne extends ModelBase
{
  //fields
    ModelRenderer fuduan;
    ModelRenderer fuding;
    ModelRenderer fubing;
    ModelRenderer fusheng1;
    ModelRenderer furen34;
    ModelRenderer furen33;
    ModelRenderer furen31;
    ModelRenderer furen21;
    ModelRenderer furen11;
    ModelRenderer fusheng21;
    ModelRenderer fusheng22;
    ModelRenderer furen12;
    ModelRenderer furen13;
    ModelRenderer furen22;
    ModelRenderer furen23;
    ModelRenderer furen32;
  
  public ModelFuOne()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      fuduan = new ModelRenderer(this, 0, 121);
      fuduan.addBox(-2F, 0F, -2F, 4, 3, 4);
      fuduan.setRotationPoint(0F, 20F, 0F);
      fuduan.setTextureSize(64, 128);
      fuduan.mirror = true;
      setRotation(fuduan, 0F, 0F, 0F);
      fuding = new ModelRenderer(this, 0, 59);
      fuding.addBox(-2F, 0F, -2F, 4, 4, 4);
      fuding.setRotationPoint(0F, -33F, 0F);
      fuding.setTextureSize(64, 128);
      fuding.mirror = true;
      setRotation(fuding, 0F, 0F, 0F);
      fubing = new ModelRenderer(this, 0, 68);
      fubing.addBox(-1.5F, 0F, -1.5F, 3, 49, 3);
      fubing.setRotationPoint(0F, -29F, 0F);
      fubing.setTextureSize(64, 128);
      fubing.mirror = true;
      setRotation(fubing, 0F, 0F, 0F);
      fusheng1 = new ModelRenderer(this, 38, 0);
      fusheng1.addBox(-4F, 0F, -2.5F, 8, 8, 5);
      fusheng1.setRotationPoint(0F, -28F, 0F);
      fusheng1.setTextureSize(64, 128);
      fusheng1.mirror = true;
      setRotation(fusheng1, 0F, 0F, 0F);
      furen34 = new ModelRenderer(this, 21, 0);
      furen34.addBox(0F, -8F, -0.5F, 7, 8, 1);
      furen34.setRotationPoint(-14.9F, -30.8F, 0F);
      furen34.setTextureSize(64, 128);
      furen34.mirror = true;
      setRotation(furen34, 0F, 0F, 0.9599311F);
      furen33 = new ModelRenderer(this, 21, 0);
      furen33.addBox(0F, 0F, -0.5F, 7, 8, 1);
      furen33.setRotationPoint(-14.9F, -17.2F, 0F);
      furen33.setTextureSize(64, 128);
      furen33.mirror = true;
      setRotation(furen33, 0F, 0F, -0.9599311F);
      furen31 = new ModelRenderer(this, 21, 10);
      furen31.addBox(-4F, 0F, -0.5F, 5, 7, 1);
      furen31.setRotationPoint(-11F, -30.2F, 0F);
      furen31.setTextureSize(64, 128);
      furen31.mirror = true;
      setRotation(furen31, 0F, 0F, 0.1745329F);
      furen21 = new ModelRenderer(this, 0, 0);
      furen21.addBox(0F, 0F, -1F, 4, 12, 2);
      furen21.setRotationPoint(-11F, -30F, 0F);
      furen21.setTextureSize(64, 128);
      furen21.mirror = true;
      setRotation(furen21, 0F, 0F, 0F);
      furen11 = new ModelRenderer(this, 0, 28);
      furen11.addBox(0F, 0F, -1.5F, 4, 8, 3);
      furen11.setRotationPoint(-9F, -28F, 0F);
      furen11.setTextureSize(64, 128);
      furen11.mirror = true;
      setRotation(furen11, 0F, 0F, 0F);
      fusheng21 = new ModelRenderer(this, 0, 48);
      fusheng21.addBox(-5F, -6F, -2F, 5, 6, 4);
      fusheng21.setRotationPoint(-3F, -22F, 0F);
      fusheng21.setTextureSize(64, 128);
      fusheng21.mirror = true;
      setRotation(fusheng21, 0F, 0F, 0.418879F);
      fusheng22 = new ModelRenderer(this, 0, 48);
      fusheng22.addBox(-5F, 0F, -2F, 5, 6, 4);
      fusheng22.setRotationPoint(-3F, -26F, 0F);
      fusheng22.setTextureSize(64, 128);
      fusheng22.mirror = true;
      setRotation(fusheng22, 0F, 0F, -0.418879F);
      furen12 = new ModelRenderer(this, 0, 40);
      furen12.addBox(0F, -4F, -1.5F, 4, 4, 3);
      furen12.setRotationPoint(-9F, -28F, 0F);
      furen12.setTextureSize(64, 128);
      furen12.mirror = true;
      setRotation(furen12, 0F, 0F, 0.6981317F);
      furen13 = new ModelRenderer(this, 0, 40);
      furen13.addBox(0F, 0F, -1.5F, 4, 4, 3);
      furen13.setRotationPoint(-9F, -20F, 0F);
      furen13.setTextureSize(64, 128);
      furen13.mirror = true;
      setRotation(furen13, 0F, 0F, -0.6981317F);
      furen22 = new ModelRenderer(this, 0, 20);
      furen22.addBox(0F, -5F, -1F, 6, 5, 2);
      furen22.setRotationPoint(-11F, -30F, 0F);
      furen22.setTextureSize(64, 128);
      furen22.mirror = true;
      setRotation(furen22, 0F, 0F, 0.8726646F);
      furen23 = new ModelRenderer(this, 0, 20);
      furen23.addBox(0F, 0F, -1F, 6, 5, 2);
      furen23.setRotationPoint(-11F, -18F, 0F);
      furen23.setTextureSize(64, 128);
      furen23.mirror = true;
      setRotation(furen23, 0F, 0F, -0.8726646F);
      furen32 = new ModelRenderer(this, 21, 10);
      furen32.addBox(-4F, -7F, -0.5F, 5, 7, 1);
      furen32.setRotationPoint(-11F, -17.8F, 0F);
      furen32.setTextureSize(64, 128);
      furen32.mirror = true;
      setRotation(furen32, 0F, 0F, -0.1745329F);
  }
  
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
 
  public void render(ItemStack is)
  {
  	if (RenderManager.instance.renderEngine == null) return;
      Item wand = is.getItem();
      EntityPlayer player = Minecraft.getMinecraft().thePlayer;
      GL11.glScaled(0.6, 0.6, 0.6);
      GL11.glRotated(30, 0, 0, 1);
      GL11.glTranslated(1.2, 2.8d, 0);
      float f5=0.0625f;
      //
      fuduan.render(f5);
      //tip?
      fuding.render(f5);
      //handle
      fubing.render(f5);
      //body ^^??
      fusheng1.render(f5);
      //edge
      furen34.render(f5);
      furen33.render(f5);
      furen31.render(f5);
      furen21.render(f5);
      furen11.render(f5);
      //body
      fusheng21.render(f5);
      fusheng22.render(f5);
      //edge
      furen12.render(f5);
      furen13.render(f5);
      furen22.render(f5);
      furen23.render(f5);
      furen32.render(f5);
  }
}
