// Date: 2017/2/11 11:54:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.Jackiecrazi.taoism.client.models.blocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTieZhenArchived extends ModelBase
{
  //fields
    ModelRenderer zhending;
    ModelRenderer zhendi2;
    ModelRenderer zhenshen1;
    ModelRenderer zhenshen2;
    ModelRenderer zhenshen3;
    ModelRenderer zhendi1;
    ModelRenderer zhendi3;
    ModelRenderer zhendi4;
    ModelRenderer zhenshen31;
  
  public ModelTieZhenArchived()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      zhending = new ModelRenderer(this, 0, 96);
      zhending.addBox(-7F, 0F, -7F, 14, 18, 14);
      zhending.setRotationPoint(0F, -17F, 0F);
      zhending.setTextureSize(128, 128);
      zhending.mirror = true;
      setRotation(zhending, 0F, 0F, 0F);
      zhendi2 = new ModelRenderer(this, 0, 0);
      zhendi2.addBox(-6.5F, 0F, -16F, 13, 9, 32);
      zhendi2.setRotationPoint(0F, 15F, 0F);
      zhendi2.setTextureSize(128, 128);
      zhendi2.mirror = true;
      setRotation(zhendi2, 0F, 0F, 0F);
      zhenshen1 = new ModelRenderer(this, 1, 54);
      zhenshen1.addBox(-5.5F, 0F, -14F, 11, 14, 28);
      zhenshen1.setRotationPoint(0F, 1F, 0F);
      zhenshen1.setTextureSize(128, 128);
      zhenshen1.mirror = true;
      setRotation(zhenshen1, 0F, 0F, 0F);
      zhenshen2 = new ModelRenderer(this, 1, 54);
      zhenshen2.addBox(-5.5F, 0F, -14F, 11, 14, 28);
      zhenshen2.setRotationPoint(0F, 1F, 0F);
      zhenshen2.setTextureSize(128, 128);
      zhenshen2.mirror = true;
      setRotation(zhenshen2, 0F, 1.570796F, 0F);
      zhenshen3 = new ModelRenderer(this, 0, 54);
      zhenshen3.addBox(-6F, 0F, -14F, 12, 14, 28);
      zhenshen3.setRotationPoint(0F, 1F, 0F);
      zhenshen3.setTextureSize(128, 128);
      zhenshen3.mirror = true;
      setRotation(zhenshen3, 0F, 0.7853982F, 0F);
      zhendi1 = new ModelRenderer(this, 0, 0);
      zhendi1.addBox(-6.5F, 0F, -16F, 13, 9, 32);
      zhendi1.setRotationPoint(0F, 15F, 0F);
      zhendi1.setTextureSize(128, 128);
      zhendi1.mirror = true;
      setRotation(zhendi1, 0F, 1.570796F, 0F);
      zhendi3 = new ModelRenderer(this, 0, 0);
      zhendi3.addBox(-6.5F, 0F, -16F, 13, 9, 32);
      zhendi3.setRotationPoint(0F, 15F, 0F);
      zhendi3.setTextureSize(128, 128);
      zhendi3.mirror = true;
      setRotation(zhendi3, 0F, 0.7853982F, 0F);
      zhendi4 = new ModelRenderer(this, 0, 0);
      zhendi4.addBox(-6.5F, 0F, -16F, 13, 9, 32);
      zhendi4.setRotationPoint(0F, 15F, 0F);
      zhendi4.setTextureSize(128, 128);
      zhendi4.mirror = true;
      setRotation(zhendi4, 0F, -0.7853982F, 0F);
      zhenshen31 = new ModelRenderer(this, 0, 54);
      zhenshen31.addBox(-6F, 0F, -14F, 12, 14, 28);
      zhenshen31.setRotationPoint(0F, 1F, 0F);
      zhenshen31.setTextureSize(128, 128);
      zhenshen31.mirror = true;
      setRotation(zhenshen31, 0F, -0.7853982F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    //setRotationAngles(f, f1, f2, f3, f4, f5);
    zhending.render(f5);
    zhendi2.render(f5);
    zhenshen1.render(f5);
    zhenshen2.render(f5);
    zhenshen3.render(f5);
    zhendi1.render(f5);
    zhendi3.render(f5);
    zhendi4.render(f5);
    zhenshen31.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void render(float f5){
	  zhending.render(f5);
	    zhendi2.render(f5);
	    zhenshen1.render(f5);
	    zhenshen2.render(f5);
	    zhenshen3.render(f5);
	    zhendi1.render(f5);
	    zhendi3.render(f5);
	    zhendi4.render(f5);
	    zhenshen31.render(f5);
  }

}
